# Generated by Django 4.2 on 2023-06-16 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100, verbose_name='書籍名')),
                ('subtitle', models.CharField(max_length=100, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='本文')),
                ('category', models.CharField(choices=[('ビジネス', 'ビジネス'), ('生活', '生活'), ('小説', '小説'), ('マンガ', 'マンガ'), ('その他', 'その他')], max_length=100, verbose_name='ジャンル')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Bookカバー')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookuser', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='本文')),
                ('rate', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='評価')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='book.book', verbose_name='本')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewuser', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Profiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='ニックネーム')),
                ('text', models.TextField(blank=True, null=True, verbose_name='自己紹介')),
                ('sex', models.CharField(blank=True, choices=[('男性', '男性'), ('女性', '女性')], max_length=50, null=True, verbose_name='性別')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='プロフィール画像')),
                ('outher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiels', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'db_table': 'profiels',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='profiel_connect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profiel_connect', to='book.profiel'),
        ),
    ]
