# Generated by Django 4.2 on 2023-04-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('bussines', 'ビジネス'), ('life', '生活'), ('novel', '小説'), ('comic', 'マンガ'), ('other', 'その他')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
