# Generated by Django 4.2 on 2023-05-03 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_profiel'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profiel',
            name='outher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiels', to=settings.AUTH_USER_MODEL),
        ),
    ]
