# Generated by Django 4.2 on 2023-05-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_profiel_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('ビジネス', 'ビジネス'), ('生活', '生活'), ('小説', '小説'), ('マンガ', 'マンガ'), ('その他', 'その他')], max_length=100, verbose_name='ジャンル'),
        ),
    ]
