# Generated by Django 4.2 on 2023-05-26 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='profiel_connect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profiel_connect', to='book.profiel'),
        ),
    ]
