# Generated by Django 4.2 on 2023-06-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_profiel_img_alter_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiel',
            name='sex',
            field=models.CharField(blank=True, choices=[('男性', '男性'), ('女性', '女性')], max_length=50, null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='profiel',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='自己紹介'),
        ),
    ]
